import {autoGeneratedRoutesListMap} from "../../Router/routesList";

export const customBreadCrumbsNameMap = new Map([
    ...autoGeneratedRoutesListMap,
    ['customization','Настройки'],
    // ['customization/universities','Учебные заведения'],
])