import {ReactNode} from "react";
import {CustomizationPage, EPageType} from "../pages/СustomizationPage/СustomizationPage";
import {Navigate} from "react-router-dom";
import {NotExistPage} from "../pages/NotExistPage/NotExistPage.tsx"
import {CabinetPage} from "../pages/CabinetPage/CabinetPage.tsx"
import {CalendarPage} from "../pages/CalendarPage/CalendarPage.tsx"

export interface IRoute {
    path: string,
    name: string
    component: ReactNode
    routes?: IRoute[]
}


export const routesList: IRoute[] = [
    {
        path: '/',
        name: 'Календарь',
        component: <CalendarPage/>
    },

    {
        path: '*',
        name: 'Не существует',
        component: <NotExistPage/>
    },

    {
        path: 'cabinet',
        name: 'Личный кабинет',
        component: <CabinetPage/>
    },

    {
        path: `customization/events`,
        name: 'События',
        component: <Navigate to={`/customization/events/${EPageType.table}`}/>
    },
    {
        path: `customization/events/${EPageType.table}`,
        name: 'Таблица событий',
        component: <CustomizationPage/>
    },
    {
        path: `customization/events/${EPageType.view}`,
        name: 'Событие',
        component: <CustomizationPage/>
    },
    {
        path: `customization/events/${EPageType.edit}`,
        name: 'Настройка события',
        component: <CustomizationPage/>
    },
    {
        path: `customization/events/${EPageType.add}`,
        name: 'Добавление события',
        component: <CustomizationPage/>
    },

    {
        path: `customization/tags`,
        name: 'Теги',
        component: <Navigate to={`/customization/tags/${EPageType.table}`}/>
    },
    {
        path: `customization/tags/${EPageType.table}`,
        name: 'Таблица тегов',
        component: <CustomizationPage/>
    },
    {
        path: `customization/tags/${EPageType.view}`,
        name: 'Тег',
        component: <CustomizationPage/>
    },
    {
        path: `customization/tags/${EPageType.edit}`,
        name: 'Настройка тега',
        component: <CustomizationPage/>
    },
    {
        path: `customization/tags/${EPageType.add}`,
        name: 'Добавление тега',
        component: <CustomizationPage/>
    },
]

const mapRoutesListPaths = (routesList: IRoute[]): string[] => {
    const resultArr: string[] = []

    routesList.map((item) => {
        resultArr.push(item.path)
        if (item.routes) {
            resultArr.push(...mapRoutesListPaths(item.routes))
        }
    })

    return resultArr
}

const mapRoutesListNames = (routesList: IRoute[]): [string, string][] => {
    const resultArr: [string, string][] = []

    routesList.map((item) => {
        resultArr.push([item.path, item.name])
        if (item.routes) {
            resultArr.push(...mapRoutesListNames(item.routes))
        }
    })

    return resultArr
}
export const autoGeneratedRoutesListMap = new Map(mapRoutesListNames(routesList))
export const autoGeneratedAllowedLinks = mapRoutesListPaths(routesList)